spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_online
    username: root
    password: 12345678
server:
  port: 9090
files:
  upload:
    dashimg:
      path: D:/projectImg/order_online/dashMenu/
    userimg:
      path: D:/projectImg/order_online/userImg/